### ISSUE TITLE
pandas_datareader Google Financial problem

### ISSUE THREAD

**Issue by yyashkir** [yyashkir/stock_mkt_quotes#2]
Hello, I am using this pltform:
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32

The code I'm running is this:

from pandas_datareader import data
p = data.DataReader('AMZN', 'google')

The response is:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\yashkir\Miniconda3\lib\site-packages\pandas_datareader\data.py", line 137, in DataReader
    session=session).read()
  File "C:\Users\yashkir\Miniconda3\lib\site-packages\pandas_datareader\base.py", line 181, in read
    params=self._get_params(self.symbols))
  File "C:\Users\yashkir\Miniconda3\lib\site-packages\pandas_datareader\base.py", line 79, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
  File "C:\Users\yashkir\Miniconda3\lib\site-packages\pandas_datareader\base.py", line 98, in _read_url_as_StringIO
    out.write(bytes_to_str(text))
  File "C:\Users\yashkir\Miniconda3\lib\site-packages\pandas\compat\__init__.py", line 74, in bytes_to_str
    return b.decode(encoding or 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 14574: invalid continuation byte

It worked some time ago, now I have this error.
Is it data from google financial corrupted? Or, something wrong with my miniconda/packages?

**Comment by dyashkir** [comment]
It looks like a problem with data

**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 14574: invalid continuation byte**
